[package]
name = "rubbledb"
version = "0.1.0"
authors = ["Joshua Miller <jsmiller@uchicago.edu>"]

[dependencies]
quick-error = "*"
regex = "0.1"
lazy_static = "*"
byteorder = "0.5"
snappy = "0.3.0"
itertools = "0.4.4"
